### ISSUE TITLE
Add a button/link "Report Bug" in the client that leads to a new issue on GitHub

### ISSUE THREAD

**Issue by DennisRas** [MrEliasen/path-to-power#11]
## Is this a bug report?
No

## Expected Behavior
When a user encounters a problem or have an idea for the game, they can click a button (or link) in the client that leads them to this issue tracker in a new window. The new issue will have data autofilled about the browser and operating system and player details of the user. This way they won't have to fill that out manually, and people playing the game will know where to go when reporting issues.

## Actual Behavior
Not implemented

## Possible Solution
Create a button/link to https://github.com/MrEliasen/path-to-power/issues/new?&body=xxx  

The body of the issue could be a copy of https://github.com/MrEliasen/path-to-power/blob/master/.github/ISSUE_TEMPLATE.md with some tags replaced with data below:
- Operating System
- Browser version
- Browser Plugins
- PlayerId/PlayerName

**Comment by MrEliasen** [comment]
Plugins seem to have issues loading from Firefox.
