### ISSUE TITLE
Add more authentication methods

### ISSUE THREAD

**Issue by MrEliasen** [MrEliasen/path-to-power#29]
Add user/password login method and possibly other OAuth implementations like Google.

**Comment by DennisRas** [comment]
Possible resource: http://www.passportjs.org/

**Comment by MrEliasen** [comment]
Fixed in version 0.1.0 (https://github.com/MrEliasen/path-to-power/commit/5ed4d04a17a0d663fe66e1f40840144ff69660a2)
