### ISSUE TITLE
Multiple characters

### ISSUE THREAD

**Issue by DennisRas** [MrEliasen/path-to-power#31]
## Is this a bug report?
No

## Expected Behavior
Say you are a regular player, but don't want to create a completely new account (at the moment of this issue: a new Twitch account), you can select a character you want to play or create a new one.

## Actual Behavior
1 character per account

**Comment by DennisRas** [comment]
Another suggestion: Limit the amount of characters to avoid spam and/or name squatting

**Comment by MrEliasen** [comment]
Fixed in version 0.1.0 (https://github.com/MrEliasen/path-to-power/commit/5ed4d04a17a0d663fe66e1f40840144ff69660a2)
