### ISSUE TITLE
Command: /help

### ISSUE THREAD

**Issue by DennisRas** [MrEliasen/path-to-power#34]
## Is this a bug report?
No

## Expected Behavior
If I'm ever lost I could type the command /help and get some help on how to play or what to do (in case I ignored the first message when logging in). This command is also pretty known to most CLI users as -h/--help

## Possible Solution
Add a new command to the server that prints/returns the introduction text.

**Comment by MrEliasen** [comment]
Resolved in https://github.com/MrEliasen/path-to-power/commit/6a2c61989cb45e28c8490498403e00bf464b6c7d
