### ISSUE TITLE
Separate accounts and characters

### ISSUE THREAD

**Issue by DennisRas** [MrEliasen/path-to-power#37]
## Is this a bug report?
No

## Expected Behavior
Separate the accounts and characters from eachother allowing other features such as deleting a character without deleting the account and moving/migrating/transfering characters. This will also make it easier for #31 to work. Will also affect #29 

## Actual Behavior
Everything is currently 1-1 between accounts and characters.

## Possible Solution
Whenever you login, you either create or manage/play one of your many characters.

**Comment by DennisRas** [comment]
Another suggestion: Limit the amount of characters to avoid spam and/or name squatting

**Comment by MrEliasen** [comment]
Fixed in branch https://github.com/MrEliasen/path-to-power/tree/auth-ui
