### ISSUE TITLE
Empty chat messages

### ISSUE THREAD

**Issue by DennisRas** [MrEliasen/path-to-power#49]
## Is this a bug report?
Yes

## Steps to Reproduce
1. Log into the game
2. Send either of the commands /say/global/faction with no message

## Expected Behavior
Not allowed

## Actual Behavior
An empty message is sent and displayed

![](https://i.imgur.com/Om2FIYC.png)

## Possible Solution
Require a character

**Comment by DennisRas** [comment]
Added screenshot

**Comment by MrEliasen** [comment]
Fixed in 0.1.0
