### ISSUE TITLE
Clicking "Whisper" on a player puts your cursor infront of the command

### ISSUE THREAD

**Issue by DennisRas** [MrEliasen/path-to-power#53]
## Is this a bug report?
Yes

## Environment Information

Operating System: Windows 10
Browser (+version): Chrome 63.0.3239.132

## Steps to Reproduce
1. Log into the game
2. Have another player online
3. Click the Players menu and the options next to a player
4. Click Whisper

![](https://i.imgur.com/DWvCqxC.png)

## Expected Behavior
The chat command /whisper <player> is added to your input and your cursor is at the end ready for your message.

![](https://i.imgur.com/fotyynJ.png)

## Actual Behavior
The chat command /whisper <player> is added to your input but your cursor is set to position 0.

![](https://i.imgur.com/CMPRAT8.png)

## Possible Solution
Have the cursor focus the input element after the command has been set.
May require a 0ms delayed callback in order to wait for the command input first.

**Comment by MrEliasen** [comment]
Fixed in https://github.com/MrEliasen/path-to-power/commit/563b0529160fc9f712da1dc5bd3228d800ac39b5
