### ISSUE TITLE
Command /shop has no response

### ISSUE THREAD

**Issue by DennisRas** [MrEliasen/path-to-power#56]
## Is this a bug report?
Yes

## Environment Information

Operating System: Windows 10
Browser (+version): Chrome

## Steps to Reproduce
1. Log into the game
2. Type and enter /shop

## Expected Behavior
Anything

## Actual Behavior
Nothing

## Possible Solution
If this command only works in certain situations, it should let the player know that the command can't be used when it isn't supposed to be used.

**Comment by MrEliasen** [comment]
Duplicate of #58 
Linked to #58, will be fixed in the same commit.
