### ISSUE TITLE
Disable the buttons that require a target if player has no target

### ISSUE THREAD

**Issue by DennisRas** [MrEliasen/path-to-power#57]
## Is this a bug report?
No

## Expected Behavior
Don't allow the player to click the bottom 3 buttons if I don't have a target:

![](https://i.imgur.com/p4ALYUd.png)

## Actual Behavior
Commands are sent and a message is sent back that the player has no target.

## Possible Solution
When the player has no target, the first buttons could be disabled with an indicator and a tooltip explaining why. Save some bandwidth.

**Comment by MrEliasen** [comment]
Fixed in version 0.1.0 (https://github.com/MrEliasen/path-to-power/commit/5ed4d04a17a0d663fe66e1f40840144ff69660a2)
