### ISSUE TITLE
ESLint rule "linebreak-style" causes errors on Windows

### ISSUE THREAD

**Issue by DennisRas** [MrEliasen/path-to-power#69]
## Debug Information
**Operating System**: Windows 10

## Steps to Reproduce
Checkout source code on Windows
Build or edit the source code

## Expected Behavior
No ESLint errors

## Actual Behavior
This rule unintentionally enforces Unix-style line endings, which causes errors on Windows.
This rule is by default ["unix" as the value of linebreak-style](https://eslint.org/docs/rules/linebreak-style#options).
This means that people working on the source code on Windows, will by default get linting errors as git converts LF to CRLF with checkout on Windows and converts CRLF back to LF with commits on Windows.

## Possible Solutions
1. Add _"linebreak-style": 0_ to .eslintrc
2. Tell people to change their editor settings (use LF instead of CRLF)
3. Tell people to disable the conversation of LF<->CRLF with [.gitattributes](https://help.github.com/articles/dealing-with-line-endings/#per-repository-settings)

**Comment by DennisRas** [comment]
The problem with forcing Windows users to work with LF locally (solution 2 and 3) is that some editors don't actually support LF; the most popular being notepad.exe.

The problem with disabling the rule (solution 1) is that you can accidently have CRLF endings in the source code (i.e. if the user disables the git conversion of LF/CRLF with .gitattributes) and pushes that to the repo. I don't know if this ever happens though.

**Comment by MrEliasen** [comment]
Guess we have to .gitattributes route and make sure its not modified on PRs ?
