### ISSUE TITLE
Client: Missing config.js with incorrect/missing installation

### ISSUE THREAD

**Issue by DennisRas** [MrEliasen/path-to-power#73]
## Debug Information
No, just a suggestion

## Steps to Reproduce
1. Clone/download the client
2. npm install
3. npm start

## Expected Behavior
A warning that the config.js file is missing (user didn't follow the installation instructions)

## Actual Behavior
An error that no file or folder named 'config' exists.

> ERROR in ./src/components/app/index.js
Module not found: Error: Can't resolve '../../config' in 'D:\Projekter\path-to-power\client\src\components\app'
 @ ./src/components/app/index.js 49:14-37
 @ ./src/index.js
 @ multi (webpack)-dev-server/client?http://localhost:8080 webpack-dev-server/client ./src/index.js

> ERROR in ./src/components/auth/index.js
> Module not found: Error: Can't resolve '../../config' in 'D:\Projekter\path-to-power\client\src\components\auth'
>  @ ./src/components/auth/index.js 21:14-37
>  @ ./src/components/app/index.js
>  @ ./src/index.js
>  @ multi (webpack)-dev-server/client?http://localhost:8080 webpack-dev-server/client ./src/index.js

> ERROR in ./src/components/header/index.js
> Module not found: Error: Can't resolve '../../config' in 'D:\Projekter\path-to-power\client\src\components\header'
>  @ ./src/components/header/index.js 21:14-37
>  @ ./src/components/app/index.js
>  @ ./src/index.js
>  @ multi (webpack)-dev-server/client?http://localhost:8080 webpack-dev-server/client ./src/index.js

## Possible Solution
Create a config.js check/validator similar to the server code.
Some users just run node projects with npm install and npm start/run

**Comment by DennisRas** [comment]
#74 is related

**Comment by MrEliasen** [comment]
Resolved in https://github.com/MrEliasen/path-to-power/commit/4a26d7f37a406047a40a11801d27ca8b25a56fc0
