### ISSUE TITLE
Refactor installation instructions/process

### ISSUE THREAD

**Issue by DennisRas** [MrEliasen/path-to-power#74]
So I've been downloading and installing the game a couple of times by now and I sometimes got confused because of the differences in the two when they could be similar with most of their steps. Here's my suggestion and would like to hear what you think.

## Current Client Instructions

1. Clone the repository
2. Copy  `./client/src/config.new.js` to `./client/src/config.js`
3. Add your Twitch.tv application Client Id to the new config file
4. Go to the `./client` directory
5. Run `npm install` or `yarn` to install dependencies
6. Run `npm start` or `yarn start`

If you upload the compiled client to a web server, remember to add the .htaccess file as well (ht.access in the repository, just rename it).

## Current Server Instructions

1. Create a new project on [Twitch.tv](https://dev.twitch.tv).
2. Clone the repository
3. Go to the `./server` directory
4. Run `npm install` or `yarn` to install dependencies
5. Run `npm start` or `yarn start`. 
6. At first run, it will copy the data files to a new directory and propt you for your Twitch.tv application Client Id.

You can skip step 5, if you manually moved/copied the `./server/game/data.new` to `./server/game/data`, copied  `./server/config.new.json` to `./server/config.json` and added your client id to the config.json file.

## Suggested Client Instructions

1. [Clone](https://github.com/MrEliasen/path-to-power.git) or [download](https://github.com/alebelcor/eslintrc/archive/master.zip) the repository.
2. Navigate to the **./client** directory.
3. Run `npm install` or `yarn install` to install dependencies.
4. Edit the configuration file **config.js** with your information and credentials.
5. Run `npm start` or `yarn start`

## Suggested Server Instructions

1. [Clone](https://github.com/MrEliasen/path-to-power.git) or [download](https://github.com/alebelcor/eslintrc/archive/master.zip) the repository.
2. Navigate to the **./server** directory.
3. Run `npm install` or `yarn install` to install dependencies.
4. Edit the configuration file **config.js** with your information and credentials.
5. (Optional): Edit the **/game/data/** files to fit your game
6. Run `npm start` or `yarn start`

### A couple of pointers

- Step 3 (Client and Server) should have a postinstall script: `cp -n config.sample.js config.js`.
- Step 5 (Client) and Step 6 (Server) should detect whether config.js exists and has the required details.
- Server should have requirements/prerequisites for the software needed (MongoDB and a Twitch AppId) and how to get them.

**Comment by MrEliasen** [comment]
Resolved in https://github.com/MrEliasen/path-to-power/commit/4a26d7f37a406047a40a11801d27ca8b25a56fc0
