### ISSUE TITLE
Opening the path /game reports an error

### ISSUE THREAD

**Issue by DennisRas** [MrEliasen/path-to-power#79]
Imagine someone playing the game and they want to share the game with someone else while playing the game. They're gonna copy the url (https://pathtopower.online/game) and share that with someone else, since that's the url for playing the game.

## Debug Information

**In-Game Name**: Liquidor
**Operating System**: Win32 
**Browser/Version**: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.167 Safari/537.36 

## Steps to Reproduce
Open the url: https://pathtopower.online/game

## Expected Behavior
Redirected to the lobby/start page.

## Actual Behavior
You get an error about the Twitch auth and no means to click a link to somewhere else. You're stuck unless you login with Twitch, but you wouldn't know what you're signing up for.

## Possible Solution
Redirect to the root page if you try to access /game being offline.

**Comment by DennisRas** [comment]
Another solution/note: Make the logo clickable to the root page. This change would be related to fixing the header in #78

**Comment by MrEliasen** [comment]
Will make title/logo clickable and redirect to / when not connected 👍
