### ISSUE TITLE
Multiple sessions bugs the game

### ISSUE THREAD

**Issue by DennisRas** [MrEliasen/path-to-power#80]
## Debug Information

**In-Game Name**: Liquidor
**Operating System**: Win32 
**Browser/Version**: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.167 Safari/537.36 

## Steps to Reproduce
1. Log into the game in one window
2. Log into the game with the same account in a new incognito window
3. Have fun

## Expected Behavior
Either of the following:
1. Logout the first session (I vote this)
2. Block the second session

## Actual Behavior
Both sessions are online and the game bugs.
Targets/Players aren't recognized in both sessions so events and logs become funky.

![](https://i.imgur.com/LgHtDDI.png)
![](https://i.imgur.com/8cP3xet.png)

## Possible Solution
See expected behaviour.

**Comment by MrEliasen** [comment]
I thought about checking for an already in-game session and disconnect it when logging in with another one.
