### ISSUE TITLE
Show command syntax/details when using a command incorrectly

### ISSUE THREAD

**Issue by DennisRas** [MrEliasen/path-to-power#82]
Suggestion.

## Debug Information

**In-Game Name**: Liquidor
**Operating System**: Win32 
**Browser/Version**: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.167 Safari/537.36 

## Steps to Reproduce
1. Log into the game
2. Type the following command `/factioncreate`

## Expected Behavior
You get an error about the missing parameters.
You get details/help about the command syntax, so you don't have to guess the params or use the /help function.

Something like:
![](https://i.imgur.com/YExDEp4.png)

## Actual Behavior
You get an error about the missing parameters.
Nothing else.

![](https://i.imgur.com/fHQvduh.png)

## Possible Solution
Print the syntax/help info after using a command incorrectly.

**Comment by MrEliasen** [comment]
That was intended for when we did the validator! Slipped through the cracks. Will add this to 0.1 milestone 👍
