### ISSUE TITLE
Description of the command /heal is outdated and broken

### ISSUE THREAD

**Issue by DennisRas** [MrEliasen/path-to-power#87]
## Debug Information

**In-Game Name**: Liquidor
**Operating System**: Win32 
**Browser/Version**: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.167 Safari/537.36 

## Steps to Reproduce
1. Log into the game
2. Type the command `/heal` at the hospital (currently usable globally because of #86 )

## Expected Behavior
New description format.

## Actual Behavior
Old description

![](https://i.imgur.com/tCmSItL.png)

## Possible Solution
Yolo

**Comment by MrEliasen** [comment]
fixed in https://github.com/MrEliasen/path-to-power/commit/db66e666d8eb5d04d32af063d6568a1f225de43b
